# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from exp import Exp
import math


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 468)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(65,70,70);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_input_output = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_output.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_input_output.setFont(font)
        self.lineEdit_input_output.setObjectName("lineEdit_input_output")
        self.verticalLayout.addWidget(self.lineEdit_input_output)
        self.label_output_minus = QtWidgets.QLabel(self.centralwidget)
        self.label_output_minus.setMinimumSize(QtCore.QSize(0, 20))
        self.label_output_minus.setStyleSheet("")
        self.label_output_minus.setText("")
        self.label_output_minus.setObjectName("label_output_minus")
        self.verticalLayout.addWidget(self.label_output_minus)
        self.label_output_infixToPostfix = QtWidgets.QLabel(self.centralwidget)
        self.label_output_infixToPostfix.setMinimumSize(QtCore.QSize(0, 40))
        self.label_output_infixToPostfix.setStyleSheet("")
        self.label_output_infixToPostfix.setText("")
        self.label_output_infixToPostfix.setObjectName("label_output_infixToPostfix")
        self.verticalLayout.addWidget(self.label_output_infixToPostfix)
        spacerItem = QtWidgets.QSpacerItem(219, 30, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.OP_factorial = QtWidgets.QPushButton(self.centralwidget)
        self.OP_factorial.clicked.connect(self.calculat_OP_factorial)
        self.OP_factorial.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_factorial.setStyleSheet("background-color: rgb(90,70,60);\n"
                                        "border-radius: 15px;\n"
                                        "color: rgb(255, 170, 0);")
        self.OP_factorial.setObjectName("OP_factorial")
        self.gridLayout.addWidget(self.OP_factorial, 3, 6, 1, 1)
        self.Num_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_9.clicked.connect(self.add_num9)
        self.Num_9.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_9.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_9.setFont(font)
        self.Num_9.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "")
        self.Num_9.setObjectName("Num_9")
        self.gridLayout.addWidget(self.Num_9, 2, 2, 1, 1)
        self.OP_plus = QtWidgets.QPushButton(self.centralwidget)
        self.OP_plus.clicked.connect(self.add_OP_plus)
        self.OP_plus.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_plus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OP_plus.setFont(font)
        self.OP_plus.setStyleSheet("background-color: rgb(90,70,60);\n"
                                   "border-radius: 15px;\n"
                                   "color: rgb(255, 170, 0);")
        self.OP_plus.setObjectName("OP_plus")
        self.gridLayout.addWidget(self.OP_plus, 3, 3, 1, 1)
        self.Num_0 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_0.clicked.connect(self.add_num0)
        self.Num_0.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_0.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_0.setFont(font)
        self.Num_0.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "\n"
                                 "")
        self.Num_0.setObjectName("Num_0")
        self.gridLayout.addWidget(self.Num_0, 3, 1, 1, 1)
        self.OP_minus = QtWidgets.QPushButton(self.centralwidget)
        self.OP_minus.clicked.connect(self.add_OP_minus)
        self.OP_minus.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_minus.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OP_minus.setFont(font)
        self.OP_minus.setStyleSheet("background-color: rgb(90,70,60);\n"
                                    "border-radius: 15px;\n"
                                    "color: rgb(255, 170, 0);")
        self.OP_minus.setObjectName("OP_minus")
        self.gridLayout.addWidget(self.OP_minus, 2, 3, 1, 1)
        self.OP_power = QtWidgets.QPushButton(self.centralwidget)
        self.OP_power.clicked.connect(self.add_OP_power)
        self.OP_power.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_power.setStyleSheet("background-color: rgb(90,70,60);\n"
                                    "border-radius: 15px;\n"
                                    "color: rgb(255, 170, 0);")
        self.OP_power.setObjectName("OP_power")
        self.gridLayout.addWidget(self.OP_power, 0, 4, 1, 1)
        self.OP_chart = QtWidgets.QPushButton(self.centralwidget)
        self.OP_chart.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_chart.setStyleSheet("background-color: rgb(90,70,60);\n"
                                    "border-radius: 15px;\n"
                                    "color: rgb(255, 170, 0);")
        self.OP_chart.setObjectName("OP_chart")
        self.gridLayout.addWidget(self.OP_chart, 1, 4, 1, 1)
        self.OP_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.OP_sqrt.clicked.connect(self.calculat_OP_sqrt)
        self.OP_sqrt.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_sqrt.setStyleSheet("background-color: rgb(90,70,60);\n"
                                   "border-radius: 15px;\n"
                                   "color: rgb(255, 170, 0);")
        self.OP_sqrt.setObjectName("OP_sqrt")
        self.gridLayout.addWidget(self.OP_sqrt, 2, 4, 1, 1)
        self.OP_reverse = QtWidgets.QPushButton(self.centralwidget)
        self.OP_reverse.clicked.connect(self.calculat_OP_reverse)
        self.OP_reverse.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_reverse.setStyleSheet("background-color: rgb(90,70,60);\n"
                                      "border-radius: 15px;\n"
                                      "color: rgb(255, 170, 0);\n"
                                      "")
        self.OP_reverse.setObjectName("OP_reverse")
        self.gridLayout.addWidget(self.OP_reverse, 0, 6, 1, 1)
        self.OP_abs = QtWidgets.QPushButton(self.centralwidget)
        self.OP_abs.clicked.connect(self.calculat_OP_abs)
        self.OP_abs.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_abs.setStyleSheet("background-color: rgb(90,70,60);\n"
                                  "border-radius: 15px;\n"
                                  "color: rgb(255, 170, 0);")
        self.OP_abs.setObjectName("OP_abs")
        self.gridLayout.addWidget(self.OP_abs, 2, 6, 1, 1)
        self.OP_percent = QtWidgets.QPushButton(self.centralwidget)
        self.OP_percent.clicked.connect(self.calculat_P_percent)
        self.OP_percent.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_percent.setStyleSheet("background-color: rgb(90,70,60);\n"
                                      "border-radius: 15px;\n"
                                      "color: rgb(255, 170, 0);")
        self.OP_percent.setObjectName("OP_percent")
        self.gridLayout.addWidget(self.OP_percent, 3, 4, 1, 1)
        self.OP_derivative = QtWidgets.QPushButton(self.centralwidget)
        self.OP_derivative.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_derivative.setStyleSheet("background-color: rgb(90,70,60);\n"
                                         "border-radius: 15px;\n"
                                         "color: rgb(255, 170, 0);")
        self.OP_derivative.setObjectName("OP_derivative")
        self.gridLayout.addWidget(self.OP_derivative, 1, 6, 1, 1)
        self.OP_CE = QtWidgets.QPushButton(self.centralwidget)
        self.OP_CE.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_CE.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OP_CE.setFont(font)
        self.OP_CE.setStyleSheet("background-color: rgb(253,184,44);\n"
                                 "color: rgb(0,0,0);\n"
                                 "\n"
                                 "")
        self.OP_CE.setObjectName("OP_CE")
        self.gridLayout.addWidget(self.OP_CE, 0, 8, 4, 1)
        self.Num_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_1.clicked.connect(self.add_num1)
        self.Num_1.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_1.setFont(font)
        self.Num_1.setStyleSheet("#Num_1\n"
                                 "{\n"
                                 "background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "\n"
                                 "}\n"
                                 "")
        self.Num_1.setObjectName("Num_1")
        self.gridLayout.addWidget(self.Num_1, 0, 0, 1, 1)
        self.Num_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_2.clicked.connect(self.add_num2)
        self.Num_2.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_2.setFont(font)
        self.Num_2.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "")
        self.Num_2.setObjectName("Num_2")
        self.gridLayout.addWidget(self.Num_2, 0, 1, 1, 1)
        self.OP_divide = QtWidgets.QPushButton(self.centralwidget)
        self.OP_divide.clicked.connect(self.add_OP_divide)
        self.OP_divide.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_divide.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OP_divide.setFont(font)
        self.OP_divide.setStyleSheet("background-color: rgb(90,70,60);\n"
                                     "border-radius: 15px;\n"
                                     "color: rgb(255, 170, 0);")
        self.OP_divide.setObjectName("OP_divide")
        self.gridLayout.addWidget(self.OP_divide, 0, 3, 1, 1)
        self.Num_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_5.clicked.connect(self.add_num5)
        self.Num_5.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_5.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_5.setFont(font)
        self.Num_5.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "")
        self.Num_5.setObjectName("Num_5")
        self.gridLayout.addWidget(self.Num_5, 1, 1, 1, 1)
        self.Num_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_4.clicked.connect(self.add_num4)
        self.Num_4.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_4.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_4.setFont(font)
        self.Num_4.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "\n"
                                 "")
        self.Num_4.setObjectName("Num_4")
        self.gridLayout.addWidget(self.Num_4, 1, 0, 1, 1)
        self.Num_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_3.clicked.connect(self.add_num3)
        self.Num_3.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_3.setFont(font)
        self.Num_3.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "")
        self.Num_3.setObjectName("Num_3")
        self.gridLayout.addWidget(self.Num_3, 0, 2, 1, 1)
        self.Num_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_7.clicked.connect(self.add_num7)
        self.Num_7.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_7.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_7.setFont(font)
        self.Num_7.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "")
        self.Num_7.setObjectName("Num_7")
        self.gridLayout.addWidget(self.Num_7, 2, 0, 1, 1)
        self.Num_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_6.clicked.connect(self.add_num6)
        self.Num_6.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_6.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_6.setFont(font)
        self.Num_6.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "\n"
                                 "")
        self.Num_6.setObjectName("Num_6")
        self.gridLayout.addWidget(self.Num_6, 1, 2, 1, 1)
        self.OP_multi = QtWidgets.QPushButton(self.centralwidget)
        self.OP_multi.clicked.connect(self.add_OP_multi)
        self.OP_multi.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_multi.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OP_multi.setFont(font)
        self.OP_multi.setStyleSheet("background-color: rgb(90,70,60);\n"
                                    "border-radius: 15px;\n"
                                    "color: rgb(255, 170, 0);")
        self.OP_multi.setObjectName("OP_multi")
        self.gridLayout.addWidget(self.OP_multi, 1, 3, 1, 1)
        self.Num_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Num_8.clicked.connect(self.add_num8)
        self.Num_8.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_8.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_8.setFont(font)
        self.Num_8.setStyleSheet("background-color: rgb(30,30,30);\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-radius: 25px;\n"
                                 "")
        self.Num_8.setObjectName("Num_8")
        self.gridLayout.addWidget(self.Num_8, 2, 1, 1, 1)
        self.Num_dot = QtWidgets.QPushButton(self.centralwidget)
        self.Num_dot.clicked.connect(self.add_Dot)
        self.Num_dot.setMinimumSize(QtCore.QSize(50, 50))
        self.Num_dot.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Num_dot.setFont(font)
        self.Num_dot.setStyleSheet("background-color: rgb(30,30,30);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border-radius: 25px;\n"
                                   "")
        self.Num_dot.setObjectName("Num_dot")
        self.gridLayout.addWidget(self.Num_dot, 3, 0, 1, 1)
        self.OP_equal = QtWidgets.QPushButton(self.centralwidget)
        self.OP_equal.clicked.connect(self.calculat_input)
        self.OP_equal.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_equal.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OP_equal.setFont(font)
        self.OP_equal.setStyleSheet("background-color:  rgb(170, 0, 255);\n"
                                    "border-radius: 25px;\n"
                                    "")
        self.OP_equal.setObjectName("OP_equal")
        self.gridLayout.addWidget(self.OP_equal, 3, 2, 1, 1)
        self.OP_cos = QtWidgets.QPushButton(self.centralwidget)
        self.OP_cos.clicked.connect(self.calculat_OP_cos)
        self.OP_cos.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_cos.setStyleSheet("background-color: rgb(90,70,60);\n"
                                  "border-radius: 15px;\n"
                                  "color: rgb(255, 170, 0);\n"
                                  "")
        self.OP_cos.setObjectName("OP_cos")
        self.gridLayout.addWidget(self.OP_cos, 0, 7, 1, 1)
        self.OP_sin = QtWidgets.QPushButton(self.centralwidget)
        self.OP_sin.clicked.connect(self.calculat_OP_sin)
        self.OP_sin.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_sin.setStyleSheet("background-color: rgb(90,70,60);\n"
                                  "border-radius: 15px;\n"
                                  "color: rgb(255, 170, 0);\n"
                                  "")
        self.OP_sin.setObjectName("OP_sin")
        self.gridLayout.addWidget(self.OP_sin, 1, 7, 1, 1)
        self.OP_log = QtWidgets.QPushButton(self.centralwidget)
        self.OP_log.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_log.setStyleSheet("background-color: rgb(90,70,60);\n"
                                  "border-radius: 15px;\n"
                                  "color: rgb(255, 170, 0);\n"
                                  "\n"
                                  "")
        self.OP_log.setObjectName("OP_log")
        self.gridLayout.addWidget(self.OP_log, 2, 7, 1, 1)
        self.OP_mod = QtWidgets.QPushButton(self.centralwidget)
        self.OP_mod.setMinimumSize(QtCore.QSize(50, 50))
        self.OP_mod.setStyleSheet("background-color: rgb(90,70,60);\n"
                                  "border-radius: 15px;\n"
                                  "color: rgb(255, 170, 0);\n"
                                  "")
        self.OP_mod.setObjectName("OP_mod")
        self.gridLayout.addWidget(self.OP_mod, 3, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OP_factorial.setText(_translate("MainWindow", "N!"))
        self.Num_9.setText(_translate("MainWindow", "9"))
        self.OP_plus.setText(_translate("MainWindow", "+"))
        self.Num_0.setText(_translate("MainWindow", "0"))
        self.OP_minus.setText(_translate("MainWindow", "-"))
        self.OP_power.setText(_translate("MainWindow", "^"))
        self.OP_chart.setText(_translate("MainWindow", "chart"))
        self.OP_sqrt.setText(_translate("MainWindow", "sqrt"))
        self.OP_reverse.setText(_translate("MainWindow", "1/x"))
        self.OP_abs.setText(_translate("MainWindow", "|X|"))
        self.OP_percent.setText(_translate("MainWindow", "%"))
        self.OP_derivative.setText(_translate("MainWindow", "Deriv"))
        self.OP_CE.setText(_translate("MainWindow", "CE"))
        self.Num_1.setText(_translate("MainWindow", "1"))
        self.Num_2.setText(_translate("MainWindow", "2"))
        self.OP_divide.setText(_translate("MainWindow", "/"))
        self.Num_5.setText(_translate("MainWindow", "5"))
        self.Num_4.setText(_translate("MainWindow", "4"))
        self.Num_3.setText(_translate("MainWindow", "3"))
        self.Num_7.setText(_translate("MainWindow", "7"))
        self.Num_6.setText(_translate("MainWindow", "6"))
        self.OP_multi.setText(_translate("MainWindow", "*"))
        self.Num_8.setText(_translate("MainWindow", "8"))
        self.Num_dot.setText(_translate("MainWindow", "."))
        self.OP_equal.setText(_translate("MainWindow", "="))
        self.OP_cos.setText(_translate("MainWindow", "cos"))
        self.OP_sin.setText(_translate("MainWindow", "sin"))
        self.OP_log.setText(_translate("MainWindow", "log"))
        self.OP_mod.setText(_translate("MainWindow", "mod"))

    def calculat_input(self):
        input_text = str(self.lineEdit_input_output.text())
        exp_input = Exp(input_text)
        try:
            temp = exp_input.EvaluatePostfix()
            self.lineEdit_input_output.setText(str(temp[0]))
            self.label_output_minus.setText(exp_input.minus())
            final_str = exp_input.EvaluatePostfix()[1][0]
            for i in range(1, len(exp_input.EvaluatePostfix()[1])):
                final_str = final_str + '\n' + exp_input.EvaluatePostfix()[1][i]
            self.label_output_infixToPostfix.setText(final_str)
        except Exception as e:
            self.lineEdit_input_output.setText(f'Error, {e}')

    def add_Dot(self):
        self.lineEdit_input_output.insert(".")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num0(self):
        self.lineEdit_input_output.insert("0")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num1(self):
        self.lineEdit_input_output.insert("1")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num2(self):
        self.lineEdit_input_output.insert("2")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num3(self):
        self.lineEdit_input_output.insert("3")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num4(self):
        self.lineEdit_input_output.insert("4")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num5(self):
        self.lineEdit_input_output.insert("5")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num6(self):
        self.lineEdit_input_output.insert("6")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num7(self):
        self.lineEdit_input_output.insert("7")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num8(self):
        self.lineEdit_input_output.insert("8")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_num9(self):
        self.lineEdit_input_output.insert("9")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_OP_plus(self):
        self.lineEdit_input_output.insert("+")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())
#     OP_minus

    def add_OP_minus(self):
        self.lineEdit_input_output.insert("-")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_OP_divide(self):
        self.lineEdit_input_output.insert("/")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())
    def add_OP_multi(self):
        self.lineEdit_input_output.insert("*")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def add_OP_power(self):
        self.lineEdit_input_output.insert("^")
        self.label_output_infixToPostfix.setText(self.lineEdit_input_output.text())

    def calculat_OP_sqrt(self):
        result = math.sqrt(int(self.lineEdit_input_output.text()))
        self.lineEdit_input_output.setText(str(result))
    def calculat_OP_abs(self):
        float = abs(int(self.lineEdit_input_output.text()))
        self.lineEdit_input_output.setText(str(float))
    def calculat_OP_reverse(self):
        result = 1/int(self.lineEdit_input_output.text())
        self.lineEdit_input_output.setText(str(result))
    def calculat_OP_factorial(self):
        result = math.factorial(int(self.lineEdit_input_output.text()))
        self.lineEdit_input_output.setText(str(result))
    def calculat_P_percent(self):
        result = (int(self.lineEdit_input_output.text()))/100
        self.lineEdit_input_output.setText(str(result))
    def calculat_OP_sin(self):
        result = int(self.lineEdit_input_output.text())
        self.lineEdit_input_output.setText(str(math.sin(result)))
    def calculat_OP_cos(self):
        result = int(self.lineEdit_input_output.text())
        self.lineEdit_input_output.setText(str(math.cos(result)))








if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
